version: '3.7'
services:
    postgres:
        container_name: postgres_container
        image: postgres:13.1
        restart: unless-stopped
        env_file:
            - ./database.env
        volumes:
            - ./db/data/:/var/lib/postgresql/data/
            - ./scripts/01_users.sql:/docker-entrypoint-initdb.d/01_users.sql
        networks:
            - mc-bot-net
    overlord:
        container_name: mc_bot_container
        image: mathtin/mc-discord-bot:latest
        restart: unless-stopped
        env_file:
            - ./mc-bot.env
        volumes:
            - ./mc-bot.cfg:/app/mc-bot.cfg
        networks:
            - mc-bot-net
networks:
  mc-bot-net: {}
